version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    commands:
      - echo Installing dependency...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
artifacts:
  files:
    - .next/**/*
    - locales/**/*
    - public/**/*
    - package.json
    - next.config.js